server:
  port: ${port:8181}

spring:
  application:
    name: first-service
    #my:
     # servers:
      #- dev.bar.com
      #- foo.bar.com
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservices
      username: micro
      password: micro
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  devtools:
    restart:
      exclude: static/**
  
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: DEBUG
  file: app.log
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"