spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:mysql://localhost:3306/ssafy?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
    
zuul:
  routes:
   service-a:
     path: /api/**
     service-id: client-service

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file: app.log

---

server:
  port: 8801
  
spring:
  profiles:
  - zone1

eureka:
  client:
    register-with-eureka: true
    preferSameZoneEureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      zone: zone1

---

server:
  port: 8802
  
spring:
  profiles:
  - zone2

eureka:
  client:
    register-with-eureka: true
    preferSameZoneEureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      zone: zone2

---

server:
  port: 8803
  
spring:
  profiles:
  - zone3

eureka:
  client:
    register-with-eureka: true
    preferSameZoneEureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      zone: zone3
