server:
  port: 8801
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/ssafy?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: user
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

mybatis:
  type-aliases-package: com.cloud.mapper
  mapper-locations:
  - classpath:/mapper/**/*Mapper.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
   service-a:
     path: /spring/**
     service-id: client-service
   service-b:
     path: /django/**
     service-id: django-app
     
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file: app.log
  
