spring:
  application:
    name: api-gateway
server:
  port: 8801

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
   service-a:
     path: /spring/**
     service-id: client-service
   service-b:
     path: /django/**
     service-id: django-app
     
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file: app.log