spring:
  application:
    name: client-service
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
    shutdown:
      enabled: true
      
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file: app.log

---

spring:
  profiles: zone1

server:
  port: 8181
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true  # 다른 서비스가 자신을 발견할 수 있도록 정보를 Eureka에 등록
    fetch-registry: true
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1

--- 

spring:
  profiles: zone2
    
server:
  port: 8182
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true  # 다른 서비스가 자신을 발견할 수 있도록 정보를 Eureka에 등록
    fetch-registry: true
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone2

---

spring:
  profiles: zone3
    
server:
  port: 8183
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true  # 다른 서비스가 자신을 발견할 수 있도록 정보를 Eureka에 등록
    fetch-registry: true
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone3

