spring:
  application:
    name: client-service
    
server:
  port: 8181
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2
    instance-id: client-serivce
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
    shutdown:
      enabled: true
      
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file: app.log