server:
  port: 8761
 
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
spring:
  security:
    user:
      name: admin
      password: admin123
      
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file: app.log