spring:
  application:
    name: discovery-service
  security:
    user:
      name: admin
      password: admin123
      
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file: app.log
  
---
    
spring:
  profiles:
  - peer1

server:
  port: ${PORT:8761}
 
eureka:
  client:
    service-url:
      default-zone: http://localhost:8762/eureka/,http://localhost:8763/erueka/
  instance:
    hostname: localhost
    metadata-map:
      zone: zone1

---
    
spring:
  profiles:
  - peer2
  
server:
  port: ${PORT:8762}
 
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8763/erueka/
  instance:
    hostname: peer2
    metadata-map:
      zone: zone2

---
    
spring:
  profiles:
  - peer3
  
server:
  port: ${PORT:8763}
 
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/erueka/
  instance:
    hostname: peer3
    metadata-map:
      zone: zone3

